### ISSUE TITLE
The module is not offering an API for other modules to interact

### ISSUE THREAD

**Issue by jherencia** [mrmilu/drupal_site_config#2]
I think these functions (API) should be exposed by the service so other modules can use it:

```php
...
class. SiteConfigPluginBase {
...
public function getValue($siteKey, $field): mixed
public function setValue($siteKey, $field, $value): void
...
}
```

and that `SiteConfigPluginBase` should call the service instead.

**Comment by jherencia** [comment]
I'm implementing in another module a migration script that should interact with `SiteConfig` and I shouldn't need to know what kind of `storage` an specific `site_config` is using or if it is translatable or not.

**Comment by carlos-mella** [comment]
I think that makes sense to add the methods 'getValue' and 'setValue' to the service, but I think that the service should call to the Plugin  methods, something like:

```
class SiteConfigService {

public function getValue($siteKey, $field) {

    /** @var \Drupal\site_config\SiteConfigInterface $plugin */
    $plugin = $this->siteConfigManager->createInstance($siteKey);
    return $plugin->getValue($field);
}

```

What do you think @jherencia ?

**Comment by jherencia** [comment]
It makes sense.
